### ISSUE TITLE
Highlights page being created with backlink

### ISSUE THREAD

**Issue by theBenForce** [theBenForce/logseq-plugin-my-highlights#16]
Based on the [comment by Musonius](https://discuss.logseq.com/t/kindle-highlights-and-notes-plugin/4175/18).

Pages with backlinks to actual highlights are being created.

Version?

**Comment by musoniusr** [comment]
Not sure on the version of the plugin I was using, but I will attach a sample page.

Initially it was just changing the title and adding new titles to it and creating a separate link.   The separate link didn't have highlights on it but had a backlink to a page that did (also renamed)   
Then it started doing it to dozens of pages at a time. All of the highlights would be gone from all pages when this happened.

[[[highlights%2Fbook%2FManhood of humanity; the science and art of human engineering%2Fbook%2F%3A a story of the grand banks]]%2Fbook.md](https://github.com/theBenForce/logseq-plugin-my-highlights/files/8880784/highlights.2Fbook.2FManhood.of.humanity.the.science.and.art.of.human.engineering.2Fbook.2F.3A.a.story.of.the.grand.banks.2Fbook.md)

**Comment by theBenForce** [comment]
Can you provide the full title name as it appears in the import list? I bet this is a bug from some characters in the title.

**Comment by theBenForce** [comment]
Can't reproduce.
