### ISSUE TITLE
No Highlighter icon

### ISSUE THREAD

**Issue by lsharkey** [theBenForce/logseq-plugin-my-highlights#20]
I am so happy that you wrote this plugin!  I really want to use it.  But I have installed, uninstalled and reinstalled a few times, and I don't ever get the highlighter icon.  What I get instead is the plugin icon (the puzzle piece).  If I click on it, I get a tiny dialog that says `my-highlights-open-prod` and has the little pin/unpin thingy (which doesn't actually do anything;  the graphic changes, but the icon stays in place).

My particulars:
Linux (Pop OS 22.04)
Logseq 0.7.9 installed via flatpak

I tried a manual install, per your instructions in the readme in the installed package. I didn't get it to work, but I noticed something curious:
The manual install instructions say to add the files to `logseq-plugin-my-highlights` but when I install the plugin from the logseq Marketplace, the directory is named `logseq-my-highlights`.

So I tried all 4 possible combinations: 
+ Marketplace install with `logseq-my-highlights`
+ Marketplace install with dir name changed to `logseq-plugin-my-highlights`
+ Manual extraction to `logseq-plugin-my-highlights`
+ Manual extraction to `logseq-my-highlights`

Any ideas?
Thanks!

**Comment by Gitbreast** [comment]
Same situation. 
More earlier the green pen icon could show correctly, but some how, after some version(plugin or Logseq? I don't know) - the green pen icon just gone, remained a empty clickable area.
Though this does not influence the main function, still a little bit beauty problem.

**Comment by Dieterbe** [comment]
@Gitbreast thanks for that clue. you're right, the button is there, it's just "invisible". whet you hover over it, you can see it and click it. (note that "my-highlights-open-prod" must be pinned in the plugin dialog otherwise the button disappears)
![logseq-clippings_000](https://user-images.githubusercontent.com/20774/185360189-9cb99363-dc7c-4dd8-a121-a245efdfe25f.png)

**Comment by Gitbreast** [comment]
@Dieterbe You can also leave it in the list which means do not pin it. Just click the little empty area on the left side of the plugin name, it still works!
![image](https://user-images.githubusercontent.com/96460796/185444322-cdfbd366-d20b-4be3-8b69-49242be40763.png)

**Comment by lsharkey** [comment]
@Gitbreast, @Dieterbe - Thanks for this!  I am now at version 0.8.1, and the problem is still there, but this is a usable workaround.  Both of your suggestions work for me.  Greatly appreciate your input!

**Comment by Dieterbe** [comment]
hope it works for you. i'm still stuck due to #21

**Comment by Gitbreast** [comment]
@Dieterbe @lsharkey 
Took me some time to locate the problem and figure out how to modify in `custom.css`. Finally I made it! Even change the color! Just paste the code below to `custom.css` in Logseq setting then the icon shall be jump out!
```
/*pinned icon and color*/
#logseq-my-highlights--my-highlights-open-prod .button [viewBox] {
  width: 16px;
  height: 32px;
}
#logseq-my-highlights--my-highlights-open-prod .button [viewBox] [d]{
  fill: #cccccc;
}

/*plugin list icon and color*/
#logseq-my-highlights--pl-my-highlights-open-prod .button [viewBox] {
  width: 16px;
  height: 32px;
}
#logseq-my-highlights--pl-my-highlights-open-prod .button [viewBox] [d]{
  fill: #cccccc;
}
```
`#cccccc` is the color in HEX format, I change it to light-gray, modify as u like, if u don't need it , just del that two whole parts about color!

**Comment by Gitbreast** [comment]
@theBenForce It seems like cause this svg element does not have a width and height data.
![image](https://user-images.githubusercontent.com/96460796/185459213-d2a6bdc9-54d9-4b3d-875d-3b239df54e62.png)     ![image](https://user-images.githubusercontent.com/96460796/185459048-9c96e70a-551e-4637-a697-ada419c3e228.png)

**Comment by theBenForce** [comment]
Thank you for doing all this work figuring out the issue! I'll get an update out tonight!

**Comment by theBenForce** [comment]
@Dieterbe sorry that it's taken so long to get that issue fixed. I'll take a look at it later today too.

**Comment by lsharkey** [comment]
@Dieterbe - thanks for this!  Added the custom css, and it worked like a charm!

**Comment by theBenForce** [comment]
Should be working in the latest release (1.16.2). Let me know if you're still having issues!

<img width="197" alt="image" src="https://user-images.githubusercontent.com/1892467/185501059-4130c03d-8f0f-4d4c-baf6-a2409fb52bce.png">

**Comment by lsharkey** [comment]
I just tested with 1.16.2, with @Gitbreast's fix from earlier removed, and it works like a charm!

**Comment by Gitbreast** [comment]
@lsharkey Do you have the situation #19?
By the way, 1.16.2 still can change the color with this code in `custom.css`:
```
.my-highlights-open [viewBox] [d]{
  fill: #aaaaaa;
}
```

**Comment by lsharkey** [comment]
My old-fart eyes have a hard time with the green, though, so mine is yellow.   @Gitbreast - since you seemed to like the gray you used, and you did all the homework earlier today, you might want to know the selectors are a bit different now.  This works for the fill, for both the plugin list and the pinned icon:
 ```
div.my-highlights-open svg path {
    fill: #ffff44;
}
```

**Comment by lsharkey** [comment]
@Gitbreast #19 is fixed for me after updating the plugin.  How about you?

**Comment by Gitbreast** [comment]
@lsharkey No...Can't pop out the dialog after selecting the file. I guess it's a part of language problem perhaps. Still waiting @theBenForce to figure it out. 😂

**Comment by Dieterbe** [comment]
update from 1.16.0 -> 1.16.2 made the green highlighter icon appear for me. both in the plugins dropdown as well as the "icons bar" itself. thank you!
