### ISSUE TITLE
Error: Page not found

### ISSUE THREAD

**Issue by Dieterbe** [theBenForce/logseq-plugin-my-highlights#21]
Hello,
after i select the clippings.txt file, and choose books and hit the "import" button, i get this error.  
logseq version 0.7.9 on linux, and latest plugin version.
i tried manually creating the "highlights" directory in my logseq data directory, but that didn't help.
any ideas?

PS: i just bought you a couple coffees, though i would recommend you drink something healthier, like sugar free vitamin waters :) 

## with one book selected, clicking "import"
![huh](https://user-images.githubusercontent.com/20774/185363294-5eb9bef1-9d32-4096-b0cf-1f76e8b1553c.png)
## with many books selected, clicking "import"
![huh2](https://user-images.githubusercontent.com/20774/185363298-17e0d646-508f-44b4-8f9d-4fb17f0d90d3.png)

**Comment by Dieterbe** [comment]
i have just upgraded logseq from 0.7.9 to 0.8.1, and the issue is the same (i also tried manually making the highlights directory, but again, same issue)

**Comment by theBenForce** [comment]
@Dieterbe and @Gitbreast I just tested `1.16.2` and it's importing everything as expected.

Let me know if this release resolves your issues.

**Comment by lsharkey** [comment]
I ran into this problem as well.   (I am also on Linux).
I just updated to 1.16.2 and it worked.

**Comment by Dieterbe** [comment]
update from 1.16.0 -> 1.16.2 and this issue is fixed for me! thank you Ben!
