### ISSUE TITLE
Please document expected syntax in clippings file

### ISSUE THREAD

**Issue by lsharkey** [theBenForce/logseq-plugin-my-highlights#22]
Hi, I don't have a kindle; I use the web reader and the android app.  They both export in html/xms.  Can you please provide the syntax that the clippings.txt uses, so that I can transform my files to the right format?
Thanks!

**Comment by theBenForce** [comment]
There's an example clippings file that's used for testing here: https://github.com/theBenForce/logseq-plugin-my-highlights/blob/main/test_data/My%20Clippings.txt

Let me know if you need it broken down more.

**Comment by theBenForce** [comment]
How are you exporting from the web reader? I can't find the option.

**Comment by lsharkey** [comment]
Excellent, thanks!  I'm sure I can get it figured out from here.

Oh!  So sorry - I wasn't thinking clearly when I wrote that.  It is inaccurate.  **I haven't actually downloaded via the cloud reader - **just android**.

FWIW, I have heard, but have not followed up yet -- so take it with a grain of salt -- that the capability is there in cloud reader, and if you contact Amazon customer service, they will enable export from cloud reader for your account.  If I find the time to try that, I'll let you know if it's true.

**Comment by theBenForce** [comment]
No worries, I've just been trying to figure out how to get highlights out of the cloud reader with this plugin. I got excited by the idea that I could just export them! 😄

**Comment by lsharkey** [comment]
Oh, darn, now I just feel mean for giving you hope and then snatching it away... ;-)
