### ISSUE TITLE
Hide highlight-id block property

### ISSUE THREAD

**Issue by petrushy** [theBenForce/logseq-plugin-my-highlights#37]
For the user the highlight-id gives a quite noisy view. I managed to hide this by adding

:block-hidden-properties #{:highlight-id }

to the config.edn

But it would be best if this somehow automatically is done by the plugin. Or potentially as a text in the readme.

Many thanks for a nice plugin!

**Comment by theBenForce** [comment]
I wish I could add it to the config, but it's in the readme: https://github.com/theBenForce/logseq-plugin-my-highlights#hiding-highlight-id-properties

**Comment by petrushy** [comment]
Oh :) Somehow I didn't see that, sorry for the noise!

**Comment by theBenForce** [comment]
No worries, I appreciate the feedback!
