### ISSUE TITLE
create link to amazon for book title

### ISSUE THREAD

**Issue by aakhter** [theBenForce/logseq-plugin-my-highlights#7]
it would be great to be able to create a link to the amazon entry (or even better, link to the specific text in kindle).

**Comment by theBenForce** [comment]
Unfortunately I don't get enough information from the highlights file to do this, maybe when I get it updated to pull highlights from amazon.

**Comment by theBenForce** [comment]
Maybe this could be done by parsing an Amazon search like `calibre-web`: https://github.com/janeczku/calibre-web/blob/master/cps/metadata_provider/amazon.py

**Comment by theBenForce** [comment]
URL to search for a book: https://www.amazon.com/s?k=How+to+Take+Smart+Notes&i=digital-text
